audit_header: false
title: San Diego Real Estate Video Blog with Eddie Nguyen
description: Our mission at CORE Real Estate Service is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The CORE Real Estate Service, your professional San Diego Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Eddie Nguyen
  title:
  license_number: 'Cal BRE#: 01402467'
  about_markdown: |
    CORE Real Estate Services was founded by Eddie Nguyen, and the Nguyen Nguyen Team.  Before opening up Core Real Estate Services, Eddie began his real estate career working for Prudential in 2002.  In 2004, he felt he needed to bring more value to his clients, so he partnered up with a mortgage company Equity Capital Group, in Downtown San Diego, and this is where he was introduced to the mortgaged business.   He worked closely with preferred banking partners, and gain the mortgaged experience necessary to offer the best service to his clients.   After learning the mortgage business. he was recruited to work for the top Century 21 in the world, and Eddie and his team quickly developed into one of the strongest real estate teams in San Diego County.  In fact, he and his team are ranked in the top 0.5% of over 30,000 licensed agents in San Diego County.
  brand: CORE Real Estate Service
  brokerage:
  market: San Diego
  address: '2828 University Ave #107<br>San Diego, CA 92104'
  phone: 619-788-3343
  phone_type:
  phone2:
  phone2_type:
  email: ed@ednguyen.com
  url: http://www.CoreRealEstateHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.accesssandiegohomes.com/search/advanced_search/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.accesssandiegohomes.com/selling/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.accesssandiegohomes.com/search/advanced_search/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.accesssandiegohomes.com/selling/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/NguyenNguyenRealty/
  linkedin_url: https://www.linkedin.com/in/eddie-nguyen-8aaa109/
  youtube_url: https://www.youtube.com/channel/UC1BCnYUzcZUfrdfGLEldZ7Q
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Diego Real Estate Podcast with Eddie Nguyen'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from CORE Real Estate Service - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Eddie Nguyen'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#4d4f4f'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#a7c5b0'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
